=== chantysothy/KhmerUnicodeConverter/XML/fontdata.dtd
<!--
This files provides information about the internal data structure of 
a font data file for Khmer font converter.

You can validate the xml file with this command:

    xmllint fontdata.xml &hyphen;&hyphen;dtdvalid fontdata.dtd

-->

<!-- we need one fontdata element, this is the root of the document -->
<!ELEMENT fontdata (fonts)>

<!-- the version is usedfor future extension if the format, it should be '1.0' for now -->
<!ATTLIST fontdata
          version    CDATA   #REQUIRED
          >

<!-- we need at least one font element -->
<!ELEMENT fonts (font)+>

<!-- aliases element is optional but maps element not -->
<!ELEMENT font (aliases?, maps)>

<!-- the type attribute for a font is mandatory and must be an unique id
     the default attribute can be used to set a defaulf font for this type
     the inherit attribute allows to base this font on another
            (you must give a type of a previous defined font)
     the hidden attribute makes font invisible for the user 
            (usefull for incomplete base fonts for inheritence) -->
<!ATTLIST font
          type    CDATA   #REQUIRED
          default CDATA   #IMPLIED
          inherit CDATA   #IMPLIED
          hidden  (true|false) "false"
          >

<!-- we need at least one alias tag -->
<!ELEMENT aliases (alias)+>

<!-- an alias is an alternative name for this font 
    you should create one alias for every know font name with this encoding -->
<!ELEMENT alias EMPTY>

<!-- a name attribute for a alias is mandatory 
     you should create for every known fontname an alias -->
<!ATTLIST alias
          name CDATA #REQUIRED
          >

<!-- the maps for conversion
    all elements are optional -->
<!ELEMENT maps (global?, tounicode?, fromunicode?)>

<!-- global mapping used for conversion in both ways 
    one map element is mandatory -->
<!ELEMENT global (map)+>

<!-- mapping used for conversion from legacy to unicode only
    one map element is mandatory -->
<!ELEMENT tounicode (map)+>

<!-- mapping used for conversion from unicode to legacy only
    one map element is mandatory -->
<!ELEMENT fromunicode (map)+>

<!-- the map element is always empty but the attributes must have values
    the legacy attribute needs codepoints as integer, either hex (e.g. "0x31") or decimal
        more than one character is separated by ';'  (e.g. "0x45;0x65;0x33")
    the unicode attribute must have unicode characters, you can use the xml numeric 
        representation though (e.g. hex: "&#x1780;" or decimal: "&#1345;" )
        do not type zwsp, coeng, zwj and zwnj but use the entity for it, (e.g. "&coeng;áž€")
-->
<!ELEMENT map EMPTY>
<!ATTLIST map
          legacy CDATA #REQUIRED
          unicode CDATA #REQUIRED
          >

=== chantysothy/KhmerUnicodeConverter/XML/fontdata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontdata SYSTEM "fontdata.dtd" [
          <!-- the mark entity is used for conversion from unicode to legacy 
            it represents the 0x17EA character -->
          <!ENTITY mark "&#x17EA;">
          <!-- names for common characters -->
          <!ENTITY coeng "&#x17D2;">
          <!ENTITY zwsp "&#x200B;">
          <!ENTITY zwj "&#x200C;">
          <!ENTITY zwnj "&#x200D;">
          <!-- nbsp = non breaking space -->
          <!ENTITY nbsp "&#xA0;">
]>

<fontdata version="1.0">
    <fonts>
        <font type="digit" hidden="true">
            <maps>
                <global>
                    <map legacy="0x30" unicode="០"/>
                    <map legacy="0x31" unicode="១"/>
                    <map legacy="0x32" unicode="២"/>
                    <map legacy="0x33" unicode="៣"/>
                    <map legacy="0x34" unicode="៤"/>
                    <map legacy="0x35" unicode="៥"/>
                    <map legacy="0x36" unicode="៦"/>
                    <map legacy="0x37" unicode="៧"/>
                    <map legacy="0x38" unicode="៨"/>
                    <map legacy="0x39" unicode="៩"/>
                </global>
            </maps>
        </font>

        <font type="common font" inherit="digit" hidden="true">
            <maps>
                <global>
                    <map legacy="0x2b" unicode="៎"/>
                    <map legacy="0x2c" unicode="&coeng;ប"/>
                    <map legacy="0x2d" unicode="-"/>
                    <map legacy="0x2f" unicode=","/>
                    <map legacy="0x3c" unicode="&coeng;ព"/>
                    <map legacy="0x41" unicode="ៅ"/>
                    <map legacy="0x42" unicode="ព"/>
                    <map legacy="0x43" unicode="ជ"/>
                    <map legacy="0x44" unicode="ឌ"/>
                    <map legacy="0x45" unicode="ែ"/>
                    <map legacy="0x46" unicode="ធ"/>
                    <map legacy="0x47" unicode="អ"/>
                    <map legacy="0x49" unicode="ី"/>
                    <map legacy="0x4a" unicode="&coeng;ញ"/>
                    <map legacy="0x4b" unicode="គ"/>
                    <map legacy="0x4d" unicode="ំ"/>
                    <map legacy="0x4e" unicode="ណ"/>
                    <map legacy="0x4f" unicode="ឿ"/>
                    <map legacy="0x50" unicode="ភ"/>
                    <map legacy="0x51" unicode="ឈ"/>
                    <map legacy="0x52" unicode="&coeng;រ"/>
                    <map legacy="0x54" unicode="ទ"/>
                    <map legacy="0x55" unicode="ូ"/>
                    <map legacy="0x56" unicode="&coeng;វ"/>
                    <map legacy="0x57" unicode="ឺ"/>
                    <map legacy="0x58" unicode="ឃ"/>
                    <map legacy="0x59" unicode="ួ"/>
                    <map legacy="0x5a" unicode="ឍ"/>
                    <map legacy="0x5f" unicode="៍"/>
                    <map legacy="0x61" unicode="ា"/>
                    <map legacy="0x62" unicode="ប"/>
                    <map legacy="0x63" unicode="ច"/>
                    <map legacy="0x64" unicode="ដ"/>
                    <map legacy="0x65" unicode="េ"/>
                    <map legacy="0x66" unicode="ថ"/>
                    <map legacy="0x67" unicode="ង"/>
                    <map legacy="0x68" unicode="ហ"/>
                    <map legacy="0x69" unicode="ិ"/>
                    <map legacy="0x6a" unicode="ញ"/>
                    <map legacy="0x6b" unicode="ក"/>
                    <map legacy="0x6c" unicode="ល"/>
                    <map legacy="0x6d" unicode="ម"/>
                    <map legacy="0x6e" unicode="ន"/>
                    <map legacy="0x6f" unicode="ៀ"/>
                    <map legacy="0x70" unicode="ផ"/>
                    <map legacy="0x71" unicode="ឆ"/>
                    <map legacy="0x72" unicode="រ"/>
                    <map legacy="0x73" unicode="ស"/>
                    <map legacy="0x74" unicode="ត"/>
                    <map legacy="0x75" unicode="ុ"/>
                    <map legacy="0x76" unicode="វ"/>
                    <map legacy="0x77" unicode="ឹ"/>
                    <map legacy="0x78" unicode="ខ"/>
                    <map legacy="0x79" unicode="យ"/>
                    <map legacy="0x7a" unicode="ឋ"/>
                    <map legacy="0xa2" unicode="&coeng;ជ"/>
                    <map legacy="0xa7" unicode="&coeng;ធ"/>
                    <map legacy="0xa9" unicode="&coeng;ច"/>
                    <map legacy="0xb5" unicode="&coeng;ម"/>
                    <map legacy="0xb6" unicode="&coeng;ង"/>
                    <map legacy="0xbe" unicode="៏"/>
                    <map legacy="0xc4" unicode="&coeng;ឈ"/>
                    <map legacy="0xc6" unicode="&coeng;ឍ"/>
                    <map legacy="0xc7" unicode="&coeng;ឃ"/>
                    <map legacy="0xc9" unicode="ឯ"/>
                    <map legacy="0xd0" unicode="&coeng;ឌ"/>
                    <map legacy="0xd1" unicode="&coeng;ណ"/>
                    <map legacy="0xd6" unicode="&coeng;ភ"/>
                    <map legacy="0xde" unicode="&coeng;ទ"/>
                    <map legacy="0xe4" unicode="&coeng;ឆ"/>
                    <map legacy="0xe6" unicode="&coeng;ឋ"/>
                    <map legacy="0xe7" unicode="&coeng;ខ"/>
                    <map legacy="0xe9" unicode="ៃ"/>
                    <map legacy="0xf1" unicode="&coeng;ន"/>
                    <map legacy="0xf6" unicode="&coeng;ផ"/>
                    <map legacy="0xf8" unicode="&coeng;ល"/>
                    <map legacy="0xfc" unicode="&coeng;យ"/>
                    <map legacy="0xfe" unicode="&coeng;ត"/>
                    <map legacy="0x42;0xa7" unicode="ឰ"/>
                    <map legacy="0x47;0x61" unicode="អា"/>
                    <map legacy="0x2e;0x6c;0x2e" unicode="៘"/>
                </global>
                <tounicode>
                    <map legacy="0xae" unicode="&coeng;រ"/>
                    <map legacy="0xc5" unicode="ឺ"/>
                    <map legacy="0xcd" unicode="ី"/>
                    <map legacy="0xd3" unicode="ឿ"/>
                    <map legacy="0xd8" unicode="&coeng;ញ"/>
                    <map legacy="0xda" unicode="ូ"/>
                    <map legacy="0xdc" unicode="ួ"/>
                    <map legacy="0xe5" unicode="ឹ"/>
                    <map legacy="0xed" unicode="ិ"/>
                    <map legacy="0xf3" unicode="ៀ"/>
                    <map legacy="0xfa" unicode="ុ"/>
                </tounicode>
                <fromunicode>
                    <map legacy="0xae" unicode="&mark;&coeng;រ"/>
                    <map legacy="0xc5" unicode="&mark;ឺ"/>
                    <map legacy="0xcd" unicode="&mark;ី"/>
                    <map legacy="0xd3" unicode="&mark;ឿ"/>
                    <map legacy="0xd8" unicode="&mark;&coeng;ញ"/>
                    <map legacy="0xda" unicode="&mark;ូ"/>
                    <map legacy="0xdc" unicode="&mark;ួ"/>
                    <map legacy="0xe5" unicode="&mark;ឹ"/>
                    <map legacy="0xed" unicode="&mark;ិ"/>
                    <map legacy="0xf3" unicode="&mark;ៀ"/>
                    <map legacy="0xfa" unicode="&mark;ុ"/>
                    <map legacy="0x47" unicode="&#x17a3;"/>  <!-- only used in pali -->
                    <map legacy="" unicode="&zwnj;"/>
                    <map legacy="" unicode="&zwj;"/>
                    <map legacy="0x42;0x61" unicode="&mark;ញ"/>
                    <map legacy="0x75" unicode="&mark;៉"/>
                    <map legacy="0x75" unicode="&mark;៊"/>
                    <map legacy="0xfa" unicode="&mark;&mark;៊"/>
                    <map legacy="0xfa" unicode="&mark;&mark;៉"/>
                </fromunicode>
            </maps>
        </font>

        <font type="abc parent" inherit="common font" hidden="true">
            <maps>
                <global>
                    <map legacy="0x23" unicode="ិ៍"/>
                    <map legacy="0x24" unicode="៛"/>
                    <map legacy="0x25" unicode="%"/>
                    <map legacy="0x26" unicode="័"/>
                    <map legacy="0x3a" unicode="&coeng;គ"/>
                    <map legacy="0x3b" unicode="&coeng;ក"/>
                    <map legacy="0x3d" unicode="+"/>
                    <map legacy="0x40" unicode="ៗ"/>
                    <map legacy="0x48" unicode="&coeng;ហ"/>
                    <map legacy="0x53" unicode="&coeng;ថ"/>
                    <map legacy="0x5b" unicode="ឲ&coeng;យ"/>
                    <map legacy="0x5c" unicode="ឭ"/>
                    <map legacy="0x5d" unicode="ឪ"/>
                    <map legacy="0x7b" unicode="ឱ"/>
                    <map legacy="0x7c" unicode="ឮ"/>
                    <map legacy="0x7d" unicode="ឥ"/>
                    <map legacy="0x91" unicode="៊"/>
                    <map legacy="0xa1" unicode="~"/>
                    <map legacy="0xa3" unicode="ៈ"/>
                    <map legacy="0xa4" unicode="$"/>
                    <map legacy="0xa6" unicode="ឬ"/>
                    <map legacy="0xa8" unicode="៉"/>
                    <map legacy="0xaa" unicode="9"/>
                    <map legacy="0xab" unicode="ឧ"/>
                    <map legacy="0xac" unicode="ឫ"/>
                    <map legacy="0xb2" unicode="&#x201c;"/>    <!-- “ sign -->
                    <map legacy="0xb3" unicode="&#x201d;"/>    <!-- ” sign -->
                    <map legacy="0xb4" unicode="់"/>
                    <map legacy="0xba" unicode="0"/>
                    <map legacy="0xbb" unicode="ឦ"/>
                    <map legacy="0xbc" unicode="ះ"/>
                    <map legacy="0xbd" unicode="៖"/>
                    <map legacy="0xbf" unicode="."/>
                    <map legacy="0xc1" unicode="បៅ"/>
                    <map legacy="0xd7" unicode="x"/>
                    <map legacy="0xdf" unicode="&coeng;ស"/>
                    <map legacy="0xe1" unicode="បា"/>
